### ISSUE TITLE
Working state?

### ISSUE THREAD

**Issue by trickkiste** [mjekovec2/paulmann-lights#1]
Hi Matija,

thank you for this nice project. Since Paulmann GmbH themselves do not provide any lib for their stuff, your effort is greatly appreciated. However, I tried to pip install this and ran into problems. So I would like to inquire, if this project has already reached a working state? 

I was trying to install it on a Raspberry Pi 3.

Please advise on how to install this.
I got the following error, when I walked down the pip route:

```
pi@raspberrypi:~/AIY-projects-python $ pip install paulmann==0.2.1
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting paulmann==0.2.1
  Using cached https://files.pythonhosted.org/packages/be/d6/869f084fa700cfd9a553dbac76b021498973f9ebbd63d938de4cfca3883f/paulmann-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    /tmp/pip-install-NROLoX/paulmann/paulmann/__version__.pyTraceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-NROLoX/paulmann/setup.py", line 27, in <module>
        version=get_version(),
      File "/tmp/pip-install-NROLoX/paulmann/setup.py", line 16, in get_version
        return re.search(regex, read(*path)).group("version")
      File "/tmp/pip-install-NROLoX/paulmann/setup.py", line 22, in read
        with open(filename, encoding="utf-8", mode="rt") as fp:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-NROLoX/paulmann/
```

My best regards,
Markus

**Comment by trickkiste** [comment]
No worries, I got it to install with pip3 instead of pip from Python2.7!

Looking forward to playing around with this.

BTW, have you seen the java lib from 2018?
My java knowledge is to little, to get anything working there, but maybe it is of use for you as a reference point:

https://github.com/hypfvieh/paulmann-bt-lib

My best regards and many thanks
Markus

**Comment by mjekovec2** [comment]
Hi,

great, thank you. I don't use it currently as I had too much problems connecting to BTLE. The connection was completely unstable. I don't know about the Java library, I was working with Home Assistant on Raspberry and it was simpler to write a simple library.

Happy New Year and all the best,
M
